export const NETWORK = {
    ERROR: {
        AUTH: 'NETWORK.ERROR.AUTH'
    },

    STATUS_UPDATED: 'STATUS_UPDATED',
    REQUEST_STARTED: 'REQUEST_STARTED',
    REQUEST_FINISHED: 'REQUEST_FINISHED',

    STATE: {
        CONNECTED: 'NETWORK.STATUS.CONNECTED',
        DISCONNECTED: 'NETWORK.STATUS.DISCONNECTED'
    }
};
