export const LOGIN = {
    REQUEST: 'AUTH.LOGIN.REQUEST',
    RESPONSE: 'AUTH.LOGIN.RESPONSE'
};

export const LOGOUT = {
    REQUEST: 'AUTH.LOGOUT.REQUEST',
    RESPONSE: 'AUTH.LOGOUT.RESPONSE'
};

export const LOGGED_IN_USER = {
    REQUEST: 'AUTH.LOGGED_IN_USER.REQUEST',
    RESPONSE: 'AUTH.LOGGED_IN_USER.RESPONSE',
};
